CA65=ca65
AS=$(CA65)
LD65=ld65
LD=$(LD65)
CFLAGS=-std=c90 -pedantic -Werror -Wall

VERSION_MAJOR=1
VERSION_MINOR=0
VERSION_PATCHLEVEL=0

BAAAM=prodos-build/BAAAM.BIN
HELLO=prodos-build/HELLO.BIN
OBJECTS=baaam.o fixup-fake.o prodos.o

.PHONY: all
all: BAAAM-PRODOS.po
ifdef BUILDCOPY
	cp $^ ~/dl/
endif

TMPPRODOS=BAAAM-PRODOS-TMP.po
BAAAM-PRODOS.po: prodos_242.po $(BAAAM) $(HELLO) baaam.tok2
	cp prodos_242.po $(TMPPRODOS)
	prodos $(TMPPRODOS) SAVE -t BIN -a 0x1FFD $(BAAAM) BAAAM.BIN
	prodos $(TMPPRODOS) SAVE -t BIN -a 0x2000 $(HELLO) HELLO.BIN
	prodos $(TMPPRODOS) SAVE -t BAS baaam.tok2 STARTUP
	mv $(TMPPRODOS) $@

%.tok2: %.tok
	dd bs=1 if=$< of=$@ skip=2

%.tok: %.bas
	tokenize_asoft < $< > $@ || { rm $@; exit 1; }

$(HELLO): hello.o HELLO-fixup.o Makefile prodos-build
	$(LD65) -C module.cfg -o $@ hello.o HELLO-fixup.o
$(BAAAM): baaam.o BAAAM-fixup.o prodos.o Makefile prodos-build
	$(LD65) -C baaam.cfg -o $@ baaam.o BAAAM-fixup.o prodos.o

prodos-build:
	mkdir -p $@

HELLO.2000 HELLO.3000: hello.o fixup-fake.o baaam.inc Makefile module.cfg
	$(LD65) -C module.cfg -D 'STARTADDR=$$$(subst HELLO.,,$@)' -o $@ hello.o fixup-fake.o || { rm -f $@; exit 1; }

BAAAM.2000 BAAAM.3000: baaam.o fixup-fake.o prodos.o baaam.inc Makefile baaam.cfg
	$(LD65) -C baaam.cfg -D 'STARTADDR=$$$(subst BAAAM.,,$@)' -o $@ baaam.o fixup-fake.o prodos.o || { rm -f $@; exit 1; }

BAAAM-skip := -s 3

mkfixup: mkfixup.c
	gcc $(CFLAGS) -o $@ $<

%-fixup.s: NAME=$(subst -fixup.s,,$@)

%-fixup.s: %.2000 %.3000 mkfixup Makefile
	: Generate $@; \
	set -e -u -C; \
	exec >| $@.tmp; \
	echo '; AUTO-GENERATED FILE (from make)'; \
	echo '; NOTE: since this code is not counted in the'; \
	echo ';  SIZE field of the module header, it may not'; \
	echo ';  be moved successfully with the rest. However,'; \
	echo ';  that is perfectly fine as we only use it once,';\
	echo ';  from the load-in location.'; \
	echo; \
	echo '.segment "FIXUP"'; \
	echo; \
	AME=$${NAME#?}; \
	ame=$$(echo "$$AME" | tr '[:upper:]' '[:lower:]'); \
	N=$${NAME%%"$$AME"}; Name=$${N}$${ame}; \
	echo ".export $${Name}Fixup"; \
	echo; \
	echo "$${Name}Fixup:"; \
	./mkfixup $($(NAME)-skip) $(NAME).2000 $(NAME).3000; \
	: So far so good, move it into place; \
	mv $@.tmp $@

baaam.o: baaam.s baaam.inc baaam-version.inc a2firm.inc Makefile
	$(CA65) --listing baaam.lst baaam.s

%.o: %.s Makefile
	$(CA65) --listing $(subst .o,.lst,$@) $<

# Generated by this Makefile
baaam-version.inc: Makefile
	: Generate $@; \
	set -e -u -C; \
	exec >| baaam-version.inc.tmp; \
	echo '; AUTO-GENERATED FILE (from make)'; \
	echo; \
	echo '; BAAAM version (major, minor, patchlevel):'; \
	echo '.byte $(VERSION_MAJOR), $(VERSION_MINOR), $(VERSION_PATCHLEVEL)'; \
	echo '; Commit ID:'; \
	echo -n '.byte '; \
	git rev-parse HEAD | cut -b 1-8 | sed -e 's/../$$&, /g' -e 's/, $$//'; \
	exec >&-; : stop writing the file; \
	: if we got here, everything is fine, move the file into place; \
	mv baaam-version.inc.tmp $@

.PHONY: clean
clean:
	rm -fr prodos-build
	rm -f *.o *.lst *.tok2 baaam-version.inc baaam-version.inc.tmp \
	    BAAAM\#* BAAAM.2000 BAAAM.3000 mkfixup *-fixup.s \
	    BAAAM-PRODOS.po
