CA65=ca65
AS=$(CA65)
LD65=ld65
LD=$(LD65)
CFLAGS=-std=c90 -pedantic -Werror -Wall

VERSION_MAJOR=1
VERSION_MINOR=0
VERSION_PATCHLEVEL=0

BAAAM_=BAAAM\#061FFD
BAAAM=prodos-build/$(BAAAM_)
OBJECTS=baaam.o empty-fixup.o prodos.o

.PHONY: all
all: BAAAM-PRODOS.po
ifdef BUILDCOPY
	cp $^ ~/dl/
endif

TMPPRODOS=BAAAM-PRODOS-TMP.po
BAAAM-PRODOS.po: prodos_242.po $(BAAAM) baaam.tok2
	cp prodos_242.po $(TMPPRODOS)
	prodos $(TMPPRODOS) SAVE -t BIN -a 0x1FFD $(BAAAM) BAAAM.BIN
	prodos $(TMPPRODOS) SAVE -t BAS baaam.tok2 BAAAM
	mv $(TMPPRODOS) $@

%.tok2: %.tok
	dd bs=1 if=$< of=$@ skip=2

%.tok: %.bas
	tokenize_asoft < $< > $@ || { rm $@; exit 1; }

$(BAAAM): baaam.o fixup.o prodos.o Makefile prodos-build
	$(LD65) -C baaam.cfg -o $@ baaam.o fixup.o prodos.o

prodos-build:
	mkdir -p $@

BAAAM.2000 BAAAM.3000: baaam.o empty-fixup.o prodos.o Makefile
	$(LD65) -C baaam.cfg -D 'STARTADDR=$$$(subst BAAAM.,,$@)' -o $@ baaam.o empty-fixup.o prodos.o

fixup.s: Makefile BAAAM.2000 BAAAM.3000 mkfixup
	: Generate $@; \
	set -e -u -C; \
	exec >| $@.tmp; \
	echo '; AUTO-GENERATED FILE (from make)'; \
	echo '; NOTE: since this code is not counted in the'; \
	echo ';  SIZE field of the module header, it may not'; \
	echo ';  be moved successfully with the rest. However,'; \
	echo ';  that is perfectly fine as we only use it once,';\
	echo ';  from the load-in location.'; \
	echo; \
	echo '.segment "FIXUP"'; \
	echo; \
	echo '.export BaaamFixup'; \
	echo; \
	echo 'BaaamFixup:'; \
	./mkfixup -s 3 BAAAM.2000 BAAAM.3000; \
	: So far so good, move it into place; \
	mv $@.tmp $@

baaam.o: baaam.s baaam.inc baaam-version.inc a2firm.inc Makefile
	$(CA65) --listing baaam.lst baaam.s

%.o: %.s Makefile
	$(CA65) --listing $(subst .o,.lst,$@) $<

# Generated by this Makefile
baaam-version.inc: Makefile
	: Generate $@; \
	set -e -u -C; \
	exec >| baaam-version.inc.tmp; \
	echo '; AUTO-GENERATED FILE (from make)'; \
	echo; \
	echo '; BAAAM version (major, minor, patchlevel):'; \
	echo '.byte $(VERSION_MAJOR), $(VERSION_MINOR), $(VERSION_PATCHLEVEL)'; \
	echo '; Commit ID:'; \
	echo -n '.byte '; \
	git rev-parse HEAD | cut -b 1-8 | sed -e 's/../$$&, /g' -e 's/, $$//'; \
	exec >&-; : stop writing the file; \
	: if we got here, everything is fine, move the file into place; \
	mv baaam-version.inc.tmp $@

.PHONY: clean
clean:
	rm -fr prodos-build
	rm -f *.o *.lst baaam-version.inc baaam-version.inc.tmp \
	    BAAAM\#* BAAAM.2000 BAAAM.3000 mkfixup fixup.s \
	    BAAAM-PRODOS.po
