CA65=ca65
AS=$(CA65)

VERSION_MAJOR=1
VERSION_MINOR=0
VERSION_PATCHLEVEL=0

all: baaam.o

baaam.o: baaam.s baaam.inc baaam-version.inc a2firm.inc Makefile
	$(CA65) --listing baaam.lst baaam.s

# Generated by this Makefile
baaam-version.inc: Makefile
	set -e -u -C; \
	exec >| baaam-version.inc.tmp; \
	echo '; AUTO-GENERATED FILE (from make)'; \
	echo; \
	echo '; BAAAM version (major, minor, patchlevel):'; \
	echo '.byte $(VERSION_MAJOR), $(VERSION_MINOR), $(VERSION_PATCHLEVEL)'; \
	echo '; Commit ID:'; \
	echo -n '.byte '; \
	git rev-parse HEAD | cut -b 1-8 | sed -e 's/../$$&, /g' -e 's/, $$//'; \
	exec >&-; : stop writing the file; \
	: if we got here, everything is fine, move the file into place; \
	mv baaam-version.inc.tmp $@

clean:
	rm -f *.o *.lst baaam-version.inc baaam-version.inc.tmp
